export const recipes = [
  {
    id: '1',
    name: 'Paella',
    flag: 'https://www.brillante.es/wp-content/uploads/2022/11/paella-mixta.jpg',
    category: 'Arroces',
    images: ['one', 'two'],
    ingredients: ingredientsR1,
    stars: 4.5,
    author: authorR1,
  },
  {
    id: '2',
    name: 'Pasta Marinera',
    flag: 'https://www.cocinacaserayfacil.net/wp-content/uploads/2023/10/Espaguetis-a-la-marinera.jpg',
    category: 'Pastas',
    images: ['one', 'two'],
    ingredients: ingredientsR1,
    stars: 5.0,
    author: authorR1,
  },
  {
    id: '3',
    name: 'Perro Caliente',
    flag: 'https://champinonessetasdecuiva.com/wp-content/uploads/2023/08/shutterstock_1009472197-1-1.png',
    category: 'Comida Rapida',
    images: ['one', 'two'],
    ingredients: ingredientsR1,
    stars: 4.2,
    author: authorR1,
  },
  {
    id: '4',
    name: 'Hamburguesa Mixta',
    flag: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfb21WhunqYPT9gnPmFkXdYp7lU_-gd0tcv2L-gNAZn6aiCErTinl231WGqOEhKrTFutk&usqp=CAU',
    category: 'Comida Rapida',
    images: ['one', 'two'],
    ingredients: ingredientsR1,
    stars: 4.8,
    author: ['sutanito', 'pepito'],
  },
  {
    id: '5',
    name: 'Postre de Limon',
    flag: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEOadD1Mhm6DZkxmy9AYdCIQ6XrFSoyUryWw&s',
    category: 'Postres',
    images: ['one', 'two'],
    ingredients: ingredientsR1,
    stars: 3.8,
    author: authorR1,
  },
  {
    id: '6',
    name: 'Postre Tres Leches',
    flag: 'https://cdn0.recetasgratis.net/es/posts/0/1/9/torta_tres_leches_8910_orig.jpg',
    category: 'Postres',
    images: ['one', 'two'],
    ingredients: ingredientsR1,
    stars: 3.5,
    author: authorR1,
  },
];

const authorR1 = { name: 'pepito', picture: "" };
const ingredientsR1 = [{ images: ['one', 'two'], description: 'blablabla' }];
